apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
 name: product-service
 description: Product management service
 tags:
   - tanzu
 annotations:
   'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=product-service'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  system: test
